version: '3.9'
services: 
    db:
        image: 'postgres:14-alpine'
        # volumes:
        #    - db_database:/var/lib/postgres/data
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=ayush1234
            - POSTGRES_DB=OnRoadVehicleBreakdownAssistanceDatabase
    
    app:
        depends_on:
            - db
        image: 'breakdownassistant:1.0'
        build:
            context: .
        # volumes:
        #    - vechicle_data:/var/lib/tomcat7/webapps/
        ports:
            - "8080:8080"
        restart: always
        environment:
            - SPRING_DATASOURCE_URL= jdbc:postgresql://db:5432/OnRoadVehicleBreakdownAssistanceDatabase
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=ayush1234
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
# volumes:
#    db_database: {}
#    vechicle_data: {}
