apiVersion: v1
kind: Service
metadata:
  labels:
    app: on-road-vehicle-breakdown
  name: on-road-vehicle-breakdown
spec:
  ports:
    - name: on-road-vehicle-breakdown
      port: 8080
      protocol: TCP
  selector:
    app: on-road-vehicle-breakdown
  type: NodePort